import React, { useEffect } from 'react';
import { X, Printer, Download, Scale, ShieldAlert, Check } from 'lucide-react';

export default function ExportReportModal({ analysisData, onClose }) {
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [onClose]);

  if (!analysisData) return null;

  const { summary, clauses, disclaimer } = analysisData;

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadMarkdown = () => {
    let md = `# ClarifyLegal Summary Report\n`;
    md += `**Document Type:** ${summary.document_type || 'Legal Agreement'}\n`;
    md += `**Overall Risk Rating:** ${summary.overall_risk_score?.toUpperCase()}\n\n`;
    md += `## Executive Plain-English Summary\n${summary.executive_summary}\n\n`;
    md += `## Key Document Details\n`;
    md += `- Effective Date: ${summary.metadata?.effective_date || 'N/A'}\n`;
    md += `- Governing Law: ${summary.metadata?.governing_law || 'N/A'}\n`;
    md += `- Parties Involved: ${summary.metadata?.parties_involved?.join(', ') || 'N/A'}\n\n`;
    md += `## Clause Breakdown & Lawyer Questions\n\n`;

    clauses.forEach((c, idx) => {
      md += `### ${idx + 1}. ${c.title} (${c.risk_level.toUpperCase()} RISK)\n`;
      md += `**Plain English:** ${c.plain_english}\n`;
      if (c.potential_impact) md += `**Impact:** ${c.potential_impact}\n`;
      if (c.lawyer_questions?.length) {
        md += `**Questions for Lawyer:**\n`;
        c.lawyer_questions.forEach(q => md += `- ${q}\n`);
      }
      md += `\n`;
    });

    md += `---\n*${disclaimer}*\n`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ClarifyLegal-Report-${(summary.document_type || 'Contract').replace(/\s+/g, '_')}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="modal-overlay" onClick={onClose} role="dialog" aria-modal="true" aria-labelledby="modal-title">
      <div className="modal-content" onClick={(e) => e.stopPropagation()}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem', borderBottom: '1px solid var(--border-color)', pb: '1rem' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <Scale size={24} style={{ color: 'var(--accent-primary)' }} />
            <h2 id="modal-title" style={{ fontSize: '1.4rem' }}>Legal Consultation Summary Report</h2>
          </div>
          <button onClick={onClose} aria-label="Close modal" style={{ color: 'var(--text-muted)' }}>
            <X size={22} />
          </button>
        </div>

        {/* Action Buttons */}
        <div style={{ display: 'flex', gap: '0.75rem', marginBottom: '1.5rem' }}>
          <button onClick={handlePrint} className="btn-primary" style={{ padding: '0.5rem 1rem', fontSize: '0.9rem' }}>
            <Printer size={16} />
            Print Report
          </button>

          <button onClick={handleDownloadMarkdown} className="btn-secondary" style={{ padding: '0.5rem 1rem', fontSize: '0.9rem' }}>
            <Download size={16} />
            Download Markdown
          </button>
        </div>

        {/* Printable Content Area */}
        <div className="printable-report" style={{ backgroundColor: 'var(--bg-secondary)', padding: '1.5rem', borderRadius: 'var(--radius-md)', fontSize: '0.9rem', color: 'var(--text-primary)' }}>
          <div style={{ borderBottom: '2px solid var(--border-color)', paddingBottom: '1rem', marginBottom: '1rem' }}>
            <h1 style={{ fontSize: '1.5rem', marginBottom: '0.25rem' }}>{summary.document_type}</h1>
            <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>
              Report Generated by ClarifyLegal | Risk Assessment: <strong>{summary.overall_risk_score?.toUpperCase()}</strong>
            </div>
          </div>

          <div style={{ marginBottom: '1.25rem' }}>
            <h3 style={{ fontSize: '1.1rem', color: 'var(--accent-primary)', marginBottom: '0.35rem' }}>Executive Overview</h3>
            <p>{summary.executive_summary}</p>
          </div>

          <div style={{ marginBottom: '1.25rem' }}>
            <h3 style={{ fontSize: '1.1rem', color: 'var(--accent-primary)', marginBottom: '0.5rem' }}>Key Provisions & Lawyer Questions</h3>
            {clauses.map((c, idx) => (
              <div key={idx} style={{ marginBottom: '1rem', paddingBottom: '0.85rem', borderBottom: '1px solid var(--border-color)' }}>
                <div style={{ fontWeight: 700, fontSize: '0.95rem' }}>
                  {idx + 1}. {c.title} [{c.risk_level?.toUpperCase()} RISK]
                </div>
                <div style={{ marginTop: '0.25rem', color: 'var(--text-secondary)' }}>
                  <strong>Meaning:</strong> {c.plain_english}
                </div>
                {c.lawyer_questions?.length > 0 && (
                  <div style={{ marginTop: '0.35rem', color: 'var(--accent-primary)' }}>
                    <strong>Ask your lawyer:</strong>
                    <ul style={{ paddingLeft: '1.2rem', margin: 0 }}>
                      {c.lawyer_questions.map((q, qidx) => (
                        <li key={qidx}>{q}</li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            ))}
          </div>

          <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', borderTop: '1px solid var(--border-color)', paddingTop: '0.75rem', fontStyle: 'italic' }}>
            {disclaimer}
          </div>
        </div>
      </div>
    </div>
  );
}
